---
title: Creating custom quarto&nbsp;templates
author: Rob J Hyndman
date: 23 October 2024
toc: false
abstract: I will describe several quarto templates we have made for use at Monash University to create presentations, working papers, theses, exams, slides, reports, memos, and letters. These help make our outputs look professional and consistent. They are relatively easy to make if you know a little LaTeX (for pdf output) or CSS (for html output). More advanced customization is possible with the help of Lua. I will show how you can easily adapt our quarto templates to other organizations, and how to make your own templates from scratch.
format:
  presentation-beamer: default
include-in-header: preamble.tex
---

```{r}
#| label: load-packages
library(knitr)
library(ggplot2)
library(dplyr)
```

# Letter template {.fragile}

\showtemplate{letter.pdf}
\only<2>{\begin{textblock}{9}(6.5,1)
\showyaml{letter.yml}
\end{textblock}}

# Memo template

\showtemplate{memo.pdf}
\only<2>{\begin{textblock}{9}(6.5,1)
\showyaml{memo.yml}
\end{textblock}}

# Report template

\only<1-2>{\showtemplate{report.pdf}}
\only<3>{\showtemplate{report.pdf}[2]}
\only<2-3>{\begin{textblock}{9}(6.5,1)
\showyaml{report.yml}
\end{textblock}}

# Exam template

\only<1-2>{\showtemplate{exam.pdf}}
\only<3>{\showtemplate{exam.pdf}[2]}
\only<4>{\showtemplate{exam.pdf}[3]}
\only<2-4>{\begin{textblock}{9}(6.5,1)
\showyaml{exam.yml}
\end{textblock}}

# Presentation template

\only<2-3>{\showtemplate{pdfpresentation.pdf}}
\only<1>{\showtemplate{htmltemplate.png}}
\only<2-3>{\begin{textblock}{9}(6.5,1)
\showyaml{presentation.yml}
\end{textblock}}

# Working paper template

\only<1>{\showtemplate{workingpaper.pdf}}
\only<2>{\showtemplate{workingpaper.pdf}[2]}
\only<3>{\showtemplate{workingpaper.pdf}[3]}
\only<4>{\showtemplate{workingpaper.pdf}}
\only<5-6>{\showtemplate{workingpaper.pdf}[2]}
\only<7>{\showtemplate{workingpaper.pdf}[3]}
\only<4-5>{\begin{textblock}{9}(6.5,1)
\showyaml{workingpaper.yml}
\end{textblock}}
\only<6-7>{\begin{textblock}{9}(6.5,1)
\showyaml{workingpaper2.yml}
\end{textblock}}

# Thesis template

\showtemplate{thesis.pdf}
\only<2>{\begin{textblock}{9}(6.5,1)
\showyaml{thesis.yml}
\end{textblock}}

# History

* latex templates
* rmarkdown templates
* monash package

# Design choices

* Fonts
* Citations
* Monash branding

# Structure of a template

* github repo structure
* `_extension.yml`
* pandoc partials

# Template details

* letters
* memos
* working papers
* reports
* exams
* presentations
* theses

# github organization quarto-monash

* Setting up organization front page

# monash package

* For people who don't like CLI

# Adapting for your own organization
